### PR TITLE
MRG: improve downsampling behavior on `KmerMinHash`; fix `RevIndex::gather` bug around `scaled`.

### LINKED ISSUE #3343: `downsample_*` functions in minhash.rs _always_ downsample, even when downsampling is not necessary
The root cause of the 10x slowdown in the branchwater plugin (https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/463) was that `downsample_scaled` was being called on every `against` sketch, and it was creating a new sketch every time it was called - even when no downsampling needed to be done, because the scaled values match.

This is fixed in https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/464 by only doing the downsampling if the scale does not match.

I think the sourmash code base behavior is somewhat unexpected and we should avoid doing expensive work when it's not needed. But I'm not sure how to modify the function signatures appropriately.

### PR DESCRIPTION
**Pull request by ctb**
This PR does five things:

First, it swaps the implementation of `KmerMinHash::downsample_max_hash` with `KmerMinHash::downsample_scaled`, and the same for `KmerMinHashBTree`. Previously a call to `downsample_scaled` calculated the right `max_hash` from `scaled`, then called `downsample_max_hash`, which then converted `max_hash` back to `scaled`. This reverses the logic so that (slightly) less work is done and, more importantly, the code is a bit more straightforward. 

Second, it changes the `downsample_*` functions so that they do not downsample when no downsampling is needed. As part of this the method signatures are changed to take an object, rather than a reference. This lets the functions return an unmodified `KmerMinHash` when no downsampling is needed.

Third, it turns out the `downsample_*` functions didn't check to make sure that the new `scaled` value was larger than the old one, i.e. they didn't prevent upsampling. That check was added and a new error, `CannotUpsampleScaled`, was added to sourmash core.

Fourth, this uncovered a bug in `RevIndex::gather` where the query was downsampled to the match, even when the match was lower scaled. This PR rejiggers the code so that downsampling is done appropriately in the `gather` and `calculate_gather_stats`. Since `RevIndex::gather` isn't used in the the sourmash CLI, the bug only presented in the test suite and in the branchwater plugin; see https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/468 and https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/467, where a fastmultigather test had to be fixed because of the incorrect scaled values output by `RevIndex::gather`.

Fifth, it includes https://github.com/sourmash-bio/sourmash/pull/3348 from @luizirber, which adds a `Signature::try_into()` to `KmerMinHash` to support the elimination of some clones.

Because of the method signature change for the `downsample_*` functions, the sourmash-core version needs to be bumped to a new major version, 0.16.0.

It's been a fun journey! 😅 

Fixes https://github.com/sourmash-bio/sourmash/issues/3343

Some notes on further changes and performance implications:

As a consequence of the `RevIndex::gather` changes, redundant downsampling has to be done in `RevIndex::gather` and `calculate_gather_stats`, unless we want to change the method signature of `calculate_gather_stats`. I decided the PR was big enough that I didn't want to do that in addition. It should not affect most use cases where `scaled` is the same, and we will see if it results in any slowdowns over in the branchwater plugin. See https://github.com/sourmash-bio/sourmash/issues/3196 for an issue on all of this.

We could also just insist that the query scaled is the one to pay attention to, per https://github.com/sourmash-bio/sourmash/issues/2951. This would simplify the code in Python-land as well.

Overall, the performance implications of this PR are not clear. Previously downsampling was being done even when it wasn't needed, so this may speed things up quite a lot for our typical use case! On the other hand, redundant downsampling will happen in cases where there are scaled mismatches. We just need to benchmark it, I think.

Some preliminary benchmarking reported in https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/430#issuecomment-2408571735 suggests that fastgather is now much more memory effficient 🎉 so that's good!

TODO:
- [x] resolve the scaled mismatch stuff. do we return an `Err` or what if the downsampling can't be performed?
- [x] update PR description
- [x] add more tests for downsampling, and maybe for gather
- [x] play with this code over in the branchwater plugin too! https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/467

### CODE REVIEW

**Comment by ctb** [comment]
Ready for review & merge @sourmash-bio/devs !!

**Comment by ctb** [comment]
(if & when this is merged, I will cut a new core release too.)

File: src/core/src/sketch/minhash.rs [hunk 1]
```diff
@@ -1356,13 +1366,14 @@ impl KmerMinHashBTree {
...
-            let (first, second) = if self.max_hash < other.max_hash {
+        if downsample && self.scaled() != other.scaled() {
+            // downsample to the larger of the two scaled values
+            let (first, second) = if self.scaled() > other.scaled() {
                 (self, other)
             } else {
                 (other, self)
             };
-            let downsampled_mh = second.downsample_max_hash(first.max_hash)?;
+            let downsampled_mh = second.clone().downsample_scaled(first.scaled())?;
```
Comment (luizirber) [inline src/core/src/sketch/minhash.rs:1376]: I wonder if we can do (in a future PR, not this one) a new `.downsampled_iter(scaled)` for operations like `count_common`, and avoid the conversion.

The downsampled iter would iterate over values that are in the appropriate scaled value, but wouldn't need to create new minhash sketches (can reuse the largest one and stop returning values once they go over `max_hash`, for example)

**Review by luizirber — APPROVED** [review]
