### PR TITLE
MRG: adjust `Signature::name()` to return `Option<String>` instead of `filename()` and `md5sum()`

### LINKED ISSUE #3441: `Signature::name()` returns `filename()` and then `md5sum()` if `.name` is empty.
When `Signature::name` is `None`, the accessor method returns `filename()` and then `md5sum()` instead of an empty string, `""`.

This causes problems because (e.g.) `Record::from_sig` uses `name()` to construct the `Record`, but then this causes `PartialEq` to fail to match records that have empty names and are built elsewhere.  This is what is causing `intersect_manifest` to fail over in https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/538 with standalone manifests built with empty names.

In https://github.com/sourmash-bio/sourmash/pull/3434, I propose having an empty name return empty string instead.

Alternatives would be to provide a different accessor function (`raw_name()`?) or `has_name()` or something. But since no tests seem to depend on the current behavior, and nothing breaks, I think it's ok to change.

(The inspiration from this behavior was from the Python layer, where we provide a display name.)

### PR DESCRIPTION
**Pull request by ctb**
This PR adjusts `Signature::name()` to return `None` when no name is set, instead of returning first `filename()` or (if empty) `md5sum()`. It also adds `name_str()` which returns an empty string, to avoid too many `unwrap_or` scattered throughout the codebase.

Fixes https://github.com/sourmash-bio/sourmash/issues/3441

### CODE REVIEW

File: src/core/src/index/revindex/disk_revindex.rs [hunk 1]
```diff
@@ -351,7 +351,15 @@ impl RevIndexOps for RevIndex {
                         .collection
                         .record_for_dataset(dataset_id)
                         .expect("dataset not found");
-                    Some((row.name().into(), size))
+
+                    let mut name = row.name();
```
Comment (ctb) [inline src/core/src/index/revindex/disk_revindex.rs]: This is ugly - is there an idiomatic way to do this??

Comment (ctb) [reply src/core/src/index/revindex/disk_revindex.rs]: yuck: https://stackoverflow.com/questions/45343320/how-can-i-return-the-first-non-empty-string

**Comment by ctb** [comment]
@luizirber @bluegenes ready for review!

File: src/core/src/index/revindex/disk_revindex.rs (hunk 1 above)
Comment (luizirber) [reply src/core/src/index/revindex/disk_revindex.rs]: maybe?

```rust
let name = [row.name(), row.filename(), row.md5()]
    .into_iter()
    .skip_while(|v| v.is_empty())
    .next()
    .unwrap();  // guaranteed to succeed because `md5` always exists
```

File: src/core/src/signature.rs [hunk 2]
```diff
@@ -448,10 +448,8 @@ impl Signature {
     pub fn name(&self) -> String {
```
Comment (luizirber) [inline src/core/src/signature.rs]: since `r0.18.0` is not released yet, do we want to make this
`pub fn name(&self) -> Option<String> {`
instead? This wil change calls around in other places, but seems to communicate better that the name exists or not instead of getting a `.name()` call that might return `""`

File: src/core/src/index/revindex/disk_revindex.rs (hunk 1 above)
Comment (ctb) [reply src/core/src/index/revindex/disk_revindex.rs]: yeh.... :)

File: src/core/src/signature.rs (hunk 2 above)
Comment (ctb) [reply src/core/src/signature.rs]: ooh, I like it! let me give it a try 🙇

Comment (ctb) [reply src/core/src/signature.rs]: https://github.com/sourmash-bio/sourmash/pull/3434/commits/34dba548d24c1ebdebf62a96cdfc2b85a9c2527f

File: src/core/src/index/revindex/disk_revindex.rs (hunk 1 above)
Comment (ctb) [reply src/core/src/index/revindex/disk_revindex.rs]: in 0ed80c1a

**Comment by ctb** [comment]
ready for review @luizirber !

**Review by luizirber — APPROVED** [review]

File: src/core/src/signature.rs [hunk 3]
```diff
@@ -445,14 +445,13 @@ fn default_version() -> f64 {
...
-        } else if let Some(filename) = &self.filename {
-            filename.clone()
-        } else {
-            self.md5sum()
-        }
+    pub fn name(&self) -> Option<String> {
+        self.name.clone()
+    }
+
+    // return name, if not None; or "" if None.
```
Comment (luizirber) [inline src/core/src/signature.rs]: note: `//` is a comment, `///` is a docstring. This one could also serve as docs, and would show up in https://docs.rs/sourmash/
